### ISSUE TITLE
mantine V7 button 中，经常出现button外面border 蓝色的框线，为啥

### ISSUE THREAD

**Issue by cometwk** [cometwk/books#1]
在 Mantine V7 中，按钮外面出现蓝色框线，通常是因为按钮获得了焦点（focus）时，浏览器默认的焦点样式被应用了。这是浏览器为了提高可访问性和可用性，为了让用户知道哪个元素当前处于焦点状态而自动添加的一个边框样式。

### 解决办法：
1. **自定义按钮样式**：你可以通过自定义样式或 Mantine 的 `styles` 属性来去除这个焦点边框。

```tsx
import { Button } from '@mantine/core';

function Demo() {
  return (
    <Button styles={{ root: { outline: 'none' } }}>
      取消边框
    </Button>
  );
}
```

2. **使用 CSS 覆盖焦点样式**：
   如果你想在全局去除所有按钮的焦点样式，可以使用以下 CSS 来覆盖默认的焦点样式：

```css
button:focus {
  outline: none;
  box-shadow: none;
}
```

3. **使用 `:focus-visible` 进行条件渲染**：为了更好地支持键盘导航，你也可以通过 `:focus-visible` 来控制焦点边框的显示。

```css
button:focus-visible {
  outline: none;
}
```

这种方法不会影响使用键盘的用户，因为它只会在键盘操作时应用焦点样式。

你可以根据自己的需求来选择适合的方式。
