### ISSUE TITLE
采用mantine V7.15.2 组件库，请分析一下为什么 UnstyledButton 没有显示边框

### ISSUE THREAD

**Issue by cometwk** [cometwk/books#2]
我来帮您分析这个问题。

在您的代码中，虽然在 `SearchControl.module.css` 中定义了边框样式：

```css
.root {
  /* ... */
  border: 1px solid;
  
  @mixin light {
    border-color: var(--mantine-color-gray-3);
    /* ... */
  }
  /* ... */
}
```

但是 `UnstyledButton` 没有显示边框的原因是因为 Mantine V7 中的样式优先级问题。要解决这个问题，我们需要提高 CSS 类的特异性。

建议修改 `SearchControl.tsx` 文件如下：

```typescript:src/layout/DashboardLayout/components/Header/SearchControl.tsx
// ... existing code ...
    <UnstyledButton 
      {...others} 
      className={cx(classes.root, className)}
      data-button="true"  // 添加这个属性来提高特异性
    >
// ... existing code ...
```

然后在 `SearchControl.module.css` 中修改：

```css:src/layout/DashboardLayout/components/Header/SearchControl.module.css
.root[data-button] {  /* 增加选择器特异性 */
  height: 34px;
  padding-left: var(--mantine-spacing-sm);
  padding-right: 4px;
  border-radius: var(--mantine-radius-md);
  color: var(--mantine-color-placeholder);
  border: 1px solid;
  /* ... 其余样式保持不变 ... */
}
```

这样修改的原因是：
1. Mantine V7 使用了新的样式系统，有时候会有默认样式覆盖自定义样式的情况
2. 通过添加 `data-button` 属性并在 CSS 中使用属性选择器，我们提高了样式的特异性，确保我们的自定义样式能够正确应用
3. 这种方式不会破坏现有的样式结构，同时能够解决边框不显示的问题

修改后，边框应该就能正常显示了。如果还有问题，我们可以进一步检查是否有其他样式覆盖的情况。
